# Site settings
author: Michael Chapman
title: Righting Code
header-img: img/home-bg.png
email: ecssiah@gmail.com
copyright_name: Michael Chapman
description: > # this means to ignore newlines until "baseurl:"
  An exploration of the process
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: _ecssiah_
github_username:  ecssiah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
